// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Web-API-Key',
    appId: '1:544289183767:web:demo-app-id',
    messagingSenderId: '544289183767',
    projectId: 'mycitykg',
    authDomain: 'mycitykg.firebaseapp.com',
    storageBucket: 'mycitykg.appspot.com',
    measurementId: 'G-DEMO-MEASUREMENT-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Android-API-Key',
    appId: '1:544289183767:android:demo-app-id',
    messagingSenderId: '544289183767',
    projectId: 'mycitykg',
    storageBucket: 'mycitykg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-iOS-API-Key',
    appId: '1:544289183767:ios:demo-app-id',
    messagingSenderId: '544289183767',
    projectId: 'mycitykg',
    storageBucket: 'mycitykg.appspot.com',
    iosBundleId: 'com.mycitykg.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-macOS-API-Key',
    appId: '1:544289183767:macos:demo-app-id',
    messagingSenderId: '544289183767',
    projectId: 'mycitykg',
    storageBucket: 'mycitykg.appspot.com',
    iosBundleId: 'com.mycitykg.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Windows-API-Key',
    appId: '1:544289183767:windows:demo-app-id',
    messagingSenderId: '544289183767',
    projectId: 'mycitykg',
    storageBucket: 'mycitykg.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-Replace-With-Your-Linux-API-Key',
    appId: '1:544289183767:linux:demo-app-id',
    messagingSenderId: '544289183767',
    projectId: 'mycitykg',
    storageBucket: 'mycitykg.appspot.com',
  );
}
