name: mycitykg
description: Мобильное приложение для улучшения городской инфраструктуры
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  timeago: ^3.6.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_remote_config: ^4.4.6
  firebase_dynamic_links: ^5.5.6
  firebase_app_check: ^0.2.2+6
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  
  # Media & Files
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  
  # Validation
  form_validator: ^2.1.1
  
  # Animations
  lottie: ^2.7.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
